---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountkey: RDVvQ2hIbzhIb2EwZWh5MjFrV3JxV1ZqaVo2cVBzcGIvT2Zaby9IUkEyRTJYVFZkeTZvRy9kZ0hR
    Mk84aUd5djhzUHgyRXRadWtBdytBU3R5V0JBUVE9PQ==
