---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-disk-storage
  azureFile:
    secretName: azure-secret
    shareName: myfileshare
    readOnly: false