pipeline {
    agent any
    stages {
        stage ('checkout') {
            steps {
                git branch: 'main', credentialsId: 'Github_login', url: 'https://github.com/mukthiyarglobal/drupal_app_services.git'
            }
        }
        stage ('azure_login') {
            steps {
                withCredentials([azureServicePrincipal('azure_loginid')]) {
                   // some block
                }
            }
        }
        stage ('terraform init') {
            steps {
                sh 'terraform init'
                
            }
        }
        stage ('terraform plan') {
            steps {
			    sh 'terraform plan -out=tfplan'
            }
        }
        stage ('terraform action') {
            steps {
                echo "Terraform action is --> ${action}"
                sh ('terraform ${action} --auto-approve') 
            }
        }
    }
}









